version: '3.8'

services:
  facedetectionservice:
    build:
      context: .
      dockerfile: ./FaceRecoModule/Dockerfile
    ports:
      - "5678:5678"
    volumes:
      - ./FaceRecoModule:/app
    networks:
      - app-network

  guiservice:
    build:
      context: .
      dockerfile: ./PhotoClient/Dockerfile
    volumes:
      - ./PhotoClient:/app
    ### REQUIRED FOR GUI: ###
      - /tmp/.X11-unix:/tmp/.X11-unix
    environment:
      - PYTHONUNBUFFERED=1
      - DISPLAY=host.docker.internal:0
    ###                   ###
    networks:
      - app-network

  photo_server:
    build:
      context: .
      dockerfile: ./PhotoServer/Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./PhotoServer:/app
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
